# Generated by Django 2.2.5 on 2019-11-12 14:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='voice_data',
        ),
        migrations.AddField(
            model_name='resident',
            name='mfcc_audio_speaking_phrase',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='resident',
            name='mfcc_audio_speaking_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None),
        ),
    ]
