# Generated by Django 2.2.5 on 2019-10-27 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='voice_data',
        ),
    ]
