# Generated by Django 2.2.5 on 2019-11-16 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191112_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryvisitor',
            name='pending',
        ),
    ]
