# Generated by Django 2.2.5 on 2019-10-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191027_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
