# Generated by Django 2.2.5 on 2019-09-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190920_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='user',
            new_name='owner',
        ),
    ]
