# Generated by Django 2.2.5 on 2019-10-30 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_admin'),
        ('accounts', '0003_auto_20191027_0532'),
    ]

    operations = [
    ]
