# Generated by Django 2.2.5 on 2019-09-20 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190920_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='owner',
        ),
    ]
