# Generated by Django 2.2.5 on 2019-09-23 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_visitor_owner'),
        ('accounts', '0003_auto_20190919_1240'),
    ]

    operations = [
    ]
