# Generated by Django 2.2.5 on 2019-09-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20190923_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitor',
            name='cpf',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
    ]
