# Generated by Django 2.2.5 on 2019-10-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20191006_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='password',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
