# Generated by Django 2.2.5 on 2019-10-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_resident_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_visitor',
            field=models.BooleanField(default=False, verbose_name='visitor status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_service',
            field=models.BooleanField(default=False, verbose_name='service status'),
        ),
    ]
