# Generated by Django 2.2.5 on 2019-10-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20191006_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='mfcc_audio_speaking_name',
            field=models.TextField(null=True),
        ),
    ]
