# Generated by Django 2.2.5 on 2019-10-17 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condos', '0010_auto_20190927_0123'),
        ('accounts', '0011_resident_mfcc_audio_speaking_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='apartment',
        ),
        migrations.CreateModel(
            name='EntranceControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condos.Apartment')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Resident')),
            ],
        ),
        migrations.AddField(
            model_name='resident',
            name='entrance_controls',
            field=models.ManyToManyField(through='accounts.EntranceControl', to='condos.Apartment'),
        ),
    ]
