# Generated by Django 2.2.5 on 2019-10-20 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condos', '0010_auto_20190927_0123'),
        ('accounts', '0011_resident_mfcc_audio_speaking_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryVisitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('entered', models.BooleanField(default=False, verbose_name='entry status')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condos.Apartment')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Visitor')),
            ],
        ),
        migrations.AddField(
            model_name='visitor',
            name='entries',
            field=models.ManyToManyField(through='accounts.EntryVisitor', to='condos.Apartment'),
        ),
    ]
