# Generated by Django 2.2.5 on 2019-10-17 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condos', '0010_auto_20190927_0123'),
        ('accounts', '0012_auto_20191017_1338'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntranceControl',
            new_name='Entry',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='entrance_controls',
        ),
        migrations.AddField(
            model_name='resident',
            name='apartment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='condos.Apartment'),
        ),
        migrations.AddField(
            model_name='resident',
            name='entries',
            field=models.ManyToManyField(related_name='entries', through='accounts.Entry', to='condos.Apartment'),
        ),
    ]
