language: python
python:
  - "3.7"

stages:
  - lint
  - code_style
  - tests
  - deploy

env:
  - DOCKER_COMPOSE_VERSON=1.4.2

jobs:
  include:
    - stage: code_style
      script:
        - docker-compose run lint

    - stage: tests
      script:
        - docker-compose run api test

    - stage: coveralls
      install:
        - pip install coveralls
      script:
        - docker-compose run --entrypoint "/bin/sh -c" api "coverage run --source=. manage.py test"
        - docker-compose run --entrypoint "/bin/sh -c" api "coverage report"
      after_success:
        - coverage combine --append --rcfile=.coveragerc app/.coverage
        - coverage report
        - coveralls

    - stage: deploy
      install: skip
      script: skip
      deploy:
        provider: heroku
        skip_cleanup: true
        api_key:
          secure: ${HEROKU_KEY}
        app: alohomora-epsmds
        on:
          repo: fga-eps-mds/2019.2-Alohomora
          branch: devel
          
