language: python
python:
  - "3.7"

stages:
  - statical
  - deploy

env:
  - DOCKER_COMPOSE_VERSON=1.4.2

jobs:
  include:
    - stage: statical
      script:
        - docker-compose run lint
        - docker-compose run api test

    - stage: coveralls
      install:
        - pip install coveralls
      script:
        - docker-compose run --entrypoint "/bin/sh -c" api "coverage run --source=. manage.py test"
        - docker-compose run --entrypoint "/bin/sh -c" api "coverage report"
      after_script:
        - coverage combine --append --rcfile=.coveragerc app/.coverage
      after_success:
        - coverage combine --append --rcfile=.coveragerc app/.coverage
        - coverage report
        - coveralls
