language: python
python:
  - "3.7"

stages:
  - code_quality_test
  - deploy

env:
  - DOCKER_COMPOSE_VERSON=1.4.2

jobs:
  include:
    - stage: code_quality_test
      script:
        - docker-compose run lint

    - stage: code_quality_test
      script:
        - docker-compose run api test

    - stage: code_quality_test
      install:
        - pip install coveralls
      script:
        - docker-compose run --entrypoint "/bin/sh -c" api "coverage run --source=. manage.py test"
        - docker-compose run --entrypoint "/bin/sh -c" api "coverage report"
      after_success:
        - coverage combine --append --rcfile=.coveragerc app/.coverage
        - coverage report
        - coveralls

    - stage: deploy-hmg
      if: branch = devel
      before_install:
        - docker build -f docker/Dockerfile -t alohomorateam/api:devel .
      script: 
        - docker images alohomorateam/api
      after_success:
        - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
        - docker push alohomorateam/api:devel

    - stage: deploy-prod
      if: branch = master
      before_install:
        - docker build -f docker/Dockerfile -t alohomorateam/api:master .
      script: 
        - docker images alohomorateam/api
      after_success:
        - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
        - docker push alohomorateam/api:master
          
