language: python
python:
  - "3.7"

stages:
  - code_quality_tests
  - deploy

env:
  - DOCKER_COMPOSE_VERSON=1.4.2

jobs:
  include:
    # Code Style 
    - stage: code_quality_tests
      script:
        - docker-compose run lint

    # Tests
    - stage: code_quality_tests
      script:
        - docker-compose run api test

    # Code Coverage
    - stage: code_quality_tests
      install:
        - pip install coveralls
      script:
        - docker-compose run --entrypoint "/bin/sh -c" api "coverage run --source=. manage.py test"
        - docker-compose run --entrypoint "/bin/sh -c" api "coverage report"
      after_success:
        - coverage combine --append --rcfile=.coveragerc app/.coverage
        - coverage report
        - coveralls

    # Deploy HMG
    - stage: deploy
      if: branch = devel
      before_install:
        - docker build -f docker/Dockerfile -t alohomorateam/api:devel .
      script: 
        - docker images alohomorateam/api
      after_success:
        - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
        - docker push alohomorateam/api:devel

    # Deploy PROD
    - stage: deploy
      if: branch = master
      before_install:
        - docker build -f docker/Dockerfile -t alohomorateam/api:master .
      script: 
        - docker images alohomorateam/api
      after_success:
        - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
        - docker push alohomorateam/api:master
          
