version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    volumes: 
      - ./api:/api
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"

