site_name: Alohomora
nav:
- Início: 'index.md'
- Projeto:
  - 'Documento de visão': 'projeto/doc_visao.md'
- Gerência:
  - 'Plano de gerência de configuração de software': 'gerencia/plano_gcs.md'
  - 'Estrutura analítica do projeto': 'gerencia/EAP.md'
- Sprints:
  - 'Sprint 0': 'sprints/sprint_0.md'
  - 'Sprint 1': 'sprints/sprint_1.md'
  - 'Sprint 2': 'sprints/sprint_2.md'
  - 'Sprint 3': 'sprints/sprint_3.md'

theme: material
