# Generated by Django 2.2.5 on 2019-09-24 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condos', '0008_auto_20190921_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='owner',
        ),
    ]
