# Generated by Django 2.2.5 on 2019-09-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condos', '0009_remove_apartment_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='id',
        ),
        migrations.AlterField(
            model_name='block',
            name='number',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together={('number', 'block')},
        ),
    ]
