# Generated by Django 2.2.5 on 2019-10-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condos', '0010_auto_20190927_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='number',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, unique=True),
        ),
    ]
