# Generated by Django 2.2.4 on 2019-09-03 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=9)),
                ('apartment', models.IntegerField(blank=True, null=True)),
                ('block', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=9)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
    ]
