site_name: Alohomora
nav:
- Início: 'index.md'
- Projeto:
  - 'Documento de visão': 'projeto/doc_visao.md'
  - 'Documento de arquitetura': 'projeto/doc_arquitetura.md'
- Gerência:
  - 'Termo de abertura do projeto': 'gerencia/TAP.md'
  - 'Estrutura analítica do projeto': 'gerencia/EAP.md'
  - 'Plano de gerenciamento de riscos': 'gerencia/plano_riscos.md'
- Sprints:
  - 'Sprint 0': 'sprints/sprint_0.md'
  - 'Sprint 1': 'sprints/sprint_1.md'
  - 'Sprint 2': 'sprints/sprint_2.md'
  - 'Sprint 3': 'sprints/sprint_3.md'

theme: material
