# Generated by Django 2.2.5 on 2019-10-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=15, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('user_type', models.CharField(choices=[('A', 'Admin'), ('R', 'Resident'), ('V', 'Visitor')], max_length=1)),
            ],
        ),
    ]
