# Generated by Django 2.2.5 on 2019-10-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='chat_id',
            field=models.IntegerField(unique=True),
        ),
    ]
